apiVersion: v1
kind: Service
metadata:
  name: ticker-server-lb-service
  labels:
    app: ticker-server
spec:
  type: LoadBalancer 
  ports:  
   - port: 3000
     targetPort: 3000
     protocol: TCP
  selector:
   app: ticker-server
